name: pythongreet

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Print
        run: echo Installing PIP has started ..
      - uses: actions/checkout@v3.5.2
      - name: clone python-greetings repo
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Install
        run: |
          cd C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
          pip install -r requirements.txt   
        working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
                  
  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - name: Print
        run: echo Deployment to DEV has started..
      - uses: actions/checkout@v3.5.2
      - name: Clone python-greetings repo
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          ref: main
          path: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Procesi
        run: pm2 list
      - name: Start
        run: |
          cd C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
          pm2 start app.py --name greetings-app-dev -- -p 7001
        working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Stop
        run: pm2 delete greetings-app-dev; set "errorlevel=0"

  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - name: Print
        run: echo Testing on DEV has started..
      - uses: actions/checkout@v3.5.2
      - name: Clone course-js-api-framework repo
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          ref: main
          path: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Install
        run: |
          cd C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
          npm install
      #  run: npm run greetings greetings_dev
      #  working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions

  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - name: Print
        run: echo Deployment to STG has started..
      - uses: actions/checkout@v3.5.2
      - name: Clone python-greetings repo
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          ref: main
          path: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Procesi
        run: pm2 list
      - name: Start
        run: |
          cd C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
          pm2 start app.py --name greetings-app-staging -- -p 7002
        working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Stop
        run: pm2 delete greetings-app-staging ; set "errorlevel=0"
          
  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    steps:
      - name: Print
        run: echo Testing on STG has started..
      - uses: actions/checkout@v3.5.2
      - name: Clone course-js-api-framework repo
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          ref: main
          path: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Install
        run: npm install
        working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
     #   run: npm run greetings greetings_staging
     #   working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions

  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    steps:
      - name: Print
        run: echo Deployment to PRD has started..
      - uses: actions/checkout@v3.5.2
      - name: Clone python-greetings repo
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          ref: main
          path: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Procesi
        run: pm2 list
      - name: Start
        run: |
          cd C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
          pm2 start app.py --name greetings-app-preprod -- -p 7003
        working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Stop
        run: pm2 delete greetings-app-preprod ; set "errorlevel=0"

  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    steps:
      - name: Print
        run: echo Testing on PRD has started..
      - uses: actions/checkout@v3.5.2
      - name: Clone course-js-api-framework repo
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          ref: main
          path: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Install
        run: npm install
        working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
     #   run: npm run greetings greetings_preprod
     #   working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions


  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    steps:
      - name: Print
        run: echo Deployment to PROD has started..
      - uses: actions/checkout@v3.5.2
      - name: Clone python-greetings repo
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          ref: main
          path: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Procesi
        run: pm2 list
      - name: Start
        run: |
          cd C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
          pm2 start app.py --name greetings-app-prod -- -p 7004
        working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Stop
        run: pm2 delete greetings-app-prod ; set "errorlevel=0"
          
  Tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - name: Print
        run: echo Testing on PROD has started..
      - uses: actions/checkout@v3.5.2
      - name: Clone course-js-api-framework repo
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          ref: main
          path: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
      - name: Install
        run: npm install
        working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions
       # run: npm run greetings greetings_prod
       # working-directory: C:\Windows\System32\actions-runner\_work\pythonactions\pythonactions

